version: '3'
services:
    db:
        image: postgres:13.0-alpine
        restart: unless-stopped
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        expose:
            - 5432
    admin_backend:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/admin/Dockerfile
        command: sh -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
        volumes:
            - static_volume:/app_admin/static
        ports:
            - "8000:8000"
        environment:
            DEBUG: "True"
            DJANGO_DB: postgresql
            POSTGRES_HOST: db
            POSTGRES_NAME: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_PORT: 5432
    reader_backend:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/reader/Dockerfile
        command: sh -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8080"
        volumes:
            - static_volume:/app_reader/static
        ports:
            - "8080:8080"
        environment:
            DEBUG: "True"
            DJANGO_DB: postgresql
            POSTGRES_HOST: db
            POSTGRES_NAME: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_PORT: 5432
    

volumes:
    postgres_data: {}
    static_volume: {}