# Generated by Django 5.1 on 2024-08-20 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Название тэга')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Контент')),
                ('slug', models.SlugField(default='', unique=True)),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('pub_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('edit_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения')),
                ('status', models.BooleanField(choices=[(True, 'Опубликовано'), (False, 'Не опубликовано')], default=False, verbose_name='Статус')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='posts.category', verbose_name='Категория')),
                ('tags', models.ManyToManyField(to='posts.tag', verbose_name='Теги')),
            ],
        ),
    ]
