# Generated by Django 5.1 on 2024-08-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.BooleanField(choices=[(True, 'Опубликовано'), (False, 'Не опубликовано')], default=True, verbose_name='Статус'),
        ),
    ]
